package Entity;


import java.sql.Time;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;




@Entity(name = "Bus_details")
public class Bus {

    @Id		// Declaring the column as primary key by @Id annotation
    @GeneratedValue(strategy = GenerationType.IDENTITY)   // Setting the Id As Auto-increment and autogenerated   
    @Column(name="Sr_No")
    private int srNo;
    
    @Column(name = "Bus_Id")
    private int busId;

    @Column(name = "Bus_No", length = 60)		//Declaring column name in database by using @column Annotation
    private String busNo;

    @Column(name = "Route_No", length = 60)		//Declaring column name in database by using @column Annotation
    private int routeNo;

    @Column(name = "Starting_Point", length = 60)		//Declaring column name in database by using @column Annotation
    private String startingPoint;

    @Column(name = "Destination_Point", length = 60)		//Declaring column name in database by using @column Annotation
    private String destinationPoint;

    @Column(name = "Departure_Time")		//Declaring column name in database by using @column Annotation
    private Time departureTime;

    @Column(name = "Total_Capacity")		//Declaring column name in database by using @column Annotation
    private int totalCapacity;

    @Column(name = "Available_Capacity")		//Declaring column name in database by using @column Annotation
    private int availableCapacity;
    
    @Column(name="Date")
    private Date date;
    
    @OneToMany(mappedBy = "bus")
    private List<Passenger> passengers = new ArrayList<>();

public Bus() {
	super();
}

public Bus(int srNo, int busId, String busNo, int routeNo, String startingPoint, String destinationPoint,
		Time departureTime, int totalCapacity, int availableCapacity, Date date, List<Passenger> passengers) {
	super();
	this.srNo = srNo;
	this.busId = busId;
	this.busNo = busNo;
	this.routeNo = routeNo;
	this.startingPoint = startingPoint;
	this.destinationPoint = destinationPoint;
	this.departureTime = departureTime;
	this.totalCapacity = totalCapacity;
	this.availableCapacity = availableCapacity;
	this.date = date;
	this.passengers = passengers;
}

public int getSrNo() {
	return srNo;
}

public void setSrNo(int srNo) {
	this.srNo = srNo;
}

public int getBusId() {
	return busId;
}

public void setBusId(int busId) {
	this.busId = busId;
}

public String getBusNo() {
	return busNo;
}

public void setBusNo(String busNo) {
	this.busNo = busNo;
}

public int getRouteNo() {
	return routeNo;
}

public void setRouteNo(int routeNo) {
	this.routeNo = routeNo;
}

public String getStartingPoint() {
	return startingPoint;
}

public void setStartingPoint(String startingPoint) {
	this.startingPoint = startingPoint;
}

public String getDestinationPoint() {
	return destinationPoint;
}

public void setDestinationPoint(String destinationPoint) {
	this.destinationPoint = destinationPoint;
}

public Time getDepartureTime() {
	return departureTime;
}

public void setDepartureTime(Time departureTime) {
	this.departureTime = departureTime;
}

public int getTotalCapacity() {
	return totalCapacity;
}

public void setTotalCapacity(int totalCapacity) {
	this.totalCapacity = totalCapacity;
}

public int getAvailableCapacity() {
	return availableCapacity;
}

public void setAvailableCapacity(int availableCapacity) {
	this.availableCapacity = availableCapacity;
}

public Date getDate() {
	return date;
}

public void setDate(Date date) {
	this.date = date;
}

public List<Passenger> getPassengers() {
	return passengers;
}

public void setPassengers(List<Passenger> passengers) {
	this.passengers = passengers;
}



}