package Entity;


import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.CreationTimestamp;
import java.util.Date;
import javax.persistence.OneToOne;
import javax.persistence.Table;

@Entity(name = "Passenger_details")

public class Passenger {
	
	@Id			// Declaring the column as primary key by @Id annotation
	
    @GeneratedValue(strategy = GenerationType.IDENTITY)   // Setting the Id As Auto-increment and autogenerated    
	
    @Column(name = "Passenger_Id") //Declaring column name in database by using @column Annotation
	
    private int passengerId; // Intializing variable passengerId

    @Column(name = "Passenger_Name", length = 60)   //Declaring column name in database by using @column Annotation
    private String passengerName;

    @Column(name = "Passenger_Age")  		//Declaring column name in database by using @column Annotation
    private int passengerAge;

    @Column(name = "Passenger_Gender", length = 20)		//Declaring column name in database by using @column Annotation
    private String passengerGender;

    @Column(name = "Passenger_Contact", length = 40)		//Declaring column name in database by using @column Annotation
    private String passengerContact;

    @Column(name = "Passenger_Email", length = 40)		//Declaring column name in database by using @column Annotation
    private String passengerEmail;

    @Column(name = "Booking_Date")		//Declaring column name in database by using @column Annotation
    @Temporal(TemporalType.DATE)
    private java.util.Date bookingDate;

    @Column(name = "Starting_Point", length = 60)		//Declaring column name in database by using @column Annotation
    private String passengerStartingPoint;

    @Column(name = "Destination_Point", length = 60)		//Declaring column name in database by using @column Annotation
    private String passengerDestinationPoint;
    
    @CreationTimestamp
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Date_Booked",  updatable = false)		//Declaring column name in database by using @column Annotation
    private Date dateBooked;

    @Column(name = "Seat_No")		//Declaring column name in database by using @column Annotation
    private int passengerSeatNo;
    
	  
	  @ManyToOne
	  @JoinColumn(name="User_Id")
	  private User user;
	  
	  @OneToOne
	  @JoinColumn(name="Ticket_Id")
	  private Ticket ticket;
	  
	  @ManyToOne(cascade = {CascadeType.MERGE, CascadeType.REFRESH})
	  @JoinColumn(name="Sr_No")
	  private Bus bus;
    
	  
	// Super-class Constructor
    public Passenger() {
		super();
	}




	public Passenger(int passengerId, String passengerName, int passengerAge, String passengerGender,
			String passengerContact, String passengerEmail, Date bookingDate, String passengerStartingPoint,
			String passengerDestinationPoint, Date dateBooked, int passengerSeatNo,  Ticket ticket,User user,
			Bus bus) {
		
		super();
		this.passengerId = passengerId;
		this.passengerName = passengerName;
		this.passengerAge = passengerAge;
		this.passengerGender = passengerGender;
		this.passengerContact = passengerContact;
		this.passengerEmail = passengerEmail;
		this.bookingDate = bookingDate;
		this.passengerStartingPoint = passengerStartingPoint;
		this.passengerDestinationPoint = passengerDestinationPoint;
		this.dateBooked = dateBooked;
		this.passengerSeatNo = passengerSeatNo;
		this.user = user;
		this.ticket = ticket;
		this.bus = bus;
	}




	public int getPassengerId() {
		return passengerId;
	}




	public void setPassengerId(int passengerId) {
		this.passengerId = passengerId;
	}




	public String getPassengerName() {
		return passengerName;
	}




	public void setPassengerName(String passengerName) {
		this.passengerName = passengerName;
	}




	public int getPassengerAge() {
		return passengerAge;
	}




	public void setPassengerAge(int passengerAge) {
		this.passengerAge = passengerAge;
	}




	public String getPassengerGender() {
		return passengerGender;
	}




	public void setPassengerGender(String passengerGender) {
		this.passengerGender = passengerGender;
	}




	public String getPassengerContact() {
		return passengerContact;
	}




	public void setPassengerContact(String passengerContact) {
		this.passengerContact = passengerContact;
	}




	public String getPassengerEmail() {
		return passengerEmail;
	}




	public void setPassengerEmail(String passengerEmail) {
		this.passengerEmail = passengerEmail;
	}




	public java.util.Date getBookingDate() {
		return bookingDate;
	}




	public void setBookingDate(java.util.Date bookingDate) {
		this.bookingDate = bookingDate;
	}




	public String getPassengerStartingPoint() {
		return passengerStartingPoint;
	}




	public void setPassengerStartingPoint(String passengerStartingPoint) {
		this.passengerStartingPoint = passengerStartingPoint;
	}




	public String getPassengerDestinationPoint() {
		return passengerDestinationPoint;
	}




	public void setPassengerDestinationPoint(String passengerDestinationPoint) {
		this.passengerDestinationPoint = passengerDestinationPoint;
	}




	public Date getDateBooked() {
		return dateBooked;
	}




	public void setDateBooked(Date dateBooked) {
		this.dateBooked = dateBooked;
	}




	public int getPassengerSeatNo() {
		return passengerSeatNo;
	}




	public void setPassengerSeatNo(int passengerSeatNo) {
		this.passengerSeatNo = passengerSeatNo;
	}




	public User getUser() {
		return user;
	}




	public void setUser(User user) {
		this.user = user;
	}




	public Ticket getTicket() {
		return ticket;
	}




	public void setTicket(Ticket ticket) {
		this.ticket = ticket;
	}




	public Bus getBus() {
		return bus;
	}




	public void setBus(Bus bus) {
		this.bus = bus;
	}




	@Override
	public String toString() {
		return "Passenger [passengerId=" + passengerId + ", passengerName=" + passengerName + ", passengerAge="
				+ passengerAge + ", passengerGender=" + passengerGender + ", passengerContact=" + passengerContact
				+ ", passengerEmail=" + passengerEmail + ", bookingDate=" + bookingDate + ", passengerStartingPoint="
				+ passengerStartingPoint + ", passengerDestinationPoint=" + passengerDestinationPoint + ", dateBooked="
				+ dateBooked + ", passengerSeatNo=" + passengerSeatNo + ", user=" + user + ", ticket=" + ticket
				+ ", bus=" +  bus +"]";
	}

	


	



}
