name: SonarQube Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project with Maven
        working-directory: BUS_RESERVATIONSYSTEM
        run: mvn clean compile -DskipTests

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_HOST_URL: https://weaklier-intercolonially-desire.ngrok-free.dev
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
